repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
    - id: end-of-file-fixer
    - id: flake8
    - id: mixed-line-ending
    - id: requirements-txt-fixer
    - id: trailing-whitespace
- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.1.7
  hooks:
    - id: remove-tabs
    - id: remove-crlf
- repo: https://github.com/psf/black
  rev: 23.7.0
  hooks:
    - id: black
- repo: https://github.com/asottile/blacken-docs
  rev: 1.16.0
  hooks:
    - id: blacken-docs
- repo: https://github.com/timothycrosley/isort
  rev: 4.3.21-2
  hooks:
    - id: isort
      exclude: ^docs/conf\.py$
      types: [python]
      additional_dependencies: [pipreqs, pip-api, six]
      verbose: true
