on:
  push:
    branches:
      - master
  pull_request:

name: Test
jobs:
  chore:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Setup virtualenv
        run: |
          pip install -U pip
          python3 -m venv .venv

      - name: Print environment
        run: |
          source .venv/bin/activate
          python --version
          pip --version

      - name: Install all dependencies
        run: |
          source .venv/bin/activate
          pip install -r requirements.txt
          pip install -r requirements_dev.txt

      - name: Test
        run: |
          source .venv/bin/activate
          py.test
